version: '3.4'


networks:
  default:
    external:
      name: nat


services:
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  customermanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  weborderkeeper:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

