version: '3.4'



services:
  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: src\Services\Identity.API\Dockerfile


  customermanagement.api:
    image: ${DOCKER_REGISTRY}customermanagementapi
    build:
      context: .
      dockerfile: src\Services\CustomerManagement.API\Dockerfile


  weborderkeeper:
    image: ${DOCKER_REGISTRY}weborderkeeper
    build:
      context: .
      dockerfile: src\WebApps\WebOrderkeeper\Dockerfile


  product.api:
    image: ${DOCKER_REGISTRY}productapi
    build:
      context: .
      dockerfile: src\Services\Product.API\Dockerfile

