version: '3.4'



services:
  ordering.api:
    image: ${DOCKER_REGISTRY}orderingapi
    build:
      context: .
      dockerfile: src\Services\Ordering.API\Dockerfile


  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: src\Services\Identity.API\Dockerfile


  customermanagement.api:
    image: ${DOCKER_REGISTRY}customermanagementapi
    build:
      context: .
      dockerfile: src\Services\CustomerManagement.API\Dockerfile


  customer.api:
    image: ${DOCKER_REGISTRY}customerapi
    build:
      context: .
      dockerfile: src\Services\Customer.API\Dockerfile


  weborderkeeper:
    image: ${DOCKER_REGISTRY}weborderkeeper
    build:
      context: .
      dockerfile: src\WebApps\WebOrderkeeper\Dockerfile

